[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
test = "test"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
base_sepolia = "https://sepolia.base.org"